# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.iniciarButton = QtWidgets.QPushButton(self.centralwidget)
        self.iniciarButton.setGeometry(QtCore.QRect(300, 510, 75, 23))
        self.iniciarButton.setObjectName("iniciarButton")
        self.invalid = QtWidgets.QFrame(self.centralwidget)
        self.invalid.setEnabled(True)
        self.invalid.setGeometry(QtCore.QRect(240, 300, 321, 31))
        self.invalid.setAutoFillBackground(False)
        self.invalid.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.invalid.setFrameShadow(QtWidgets.QFrame.Plain)
        self.invalid.setObjectName("invalid")
        self.label = QtWidgets.QLabel(self.invalid)
        self.label.setGeometry(QtCore.QRect(70, 0, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.video = QtWidgets.QLabel(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(60, 70, 301, 211))
        self.video.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.video.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video.setText("")
        self.video.setObjectName("video")
        self.webcamLab = QtWidgets.QLabel(self.centralwidget)
        self.webcamLab.setGeometry(QtCore.QRect(180, 40, 51, 16))
        self.webcamLab.setObjectName("webcamLab")
        self.foto = QtWidgets.QLabel(self.centralwidget)
        self.foto.setGeometry(QtCore.QRect(450, 70, 301, 211))
        self.foto.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.foto.setText("")
        self.foto.setObjectName("foto")
        self.fotoLab = QtWidgets.QLabel(self.centralwidget)
        self.fotoLab.setGeometry(QtCore.QRect(560, 40, 91, 16))
        self.fotoLab.setObjectName("fotoLab")
        self.detenerButton = QtWidgets.QPushButton(self.centralwidget)
        self.detenerButton.setGeometry(QtCore.QRect(450, 510, 75, 23))
        self.detenerButton.setObjectName("detenerButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 360, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 430, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 360, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 430, 47, 13))
        self.label_5.setObjectName("label_5")
        self.nombreEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.nombreEdit.setEnabled(True)
        self.nombreEdit.setGeometry(QtCore.QRect(130, 380, 241, 31))
        self.nombreEdit.setReadOnly(True)
        self.nombreEdit.setObjectName("nombreEdit")
        self.cedulaEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.cedulaEdit.setEnabled(True)
        self.cedulaEdit.setGeometry(QtCore.QRect(130, 450, 241, 31))
        self.cedulaEdit.setReadOnly(True)
        self.cedulaEdit.setObjectName("cedulaEdit")
        self.estadoEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.estadoEdit.setEnabled(True)
        self.estadoEdit.setGeometry(QtCore.QRect(460, 450, 231, 31))
        self.estadoEdit.setReadOnly(True)
        self.estadoEdit.setObjectName("estadoEdit")
        self.carreraEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.carreraEdit.setEnabled(True)
        self.carreraEdit.setGeometry(QtCore.QRect(460, 380, 231, 31))
        self.carreraEdit.setReadOnly(True)
        self.carreraEdit.setObjectName("carreraEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.iniciarButton.setText(_translate("MainWindow", "Iniciar"))
        self.label.setText(_translate("MainWindow", "CÓDIGO QR INVÁLIDO"))
        self.webcamLab.setText(_translate("MainWindow", "Webcam"))
        self.fotoLab.setText(_translate("MainWindow", "Foto del Alumno"))
        self.detenerButton.setText(_translate("MainWindow", "Detener"))
        self.label_2.setText(_translate("MainWindow", "Nombre"))
        self.label_3.setText(_translate("MainWindow", "Cedula"))
        self.label_4.setText(_translate("MainWindow", "Carrera"))
        self.label_5.setText(_translate("MainWindow", "Estado"))

